name: Run

on:
    workflow_dispatch: # 手动触发
  schedule: # 计划任务触发
    - cron: '0 16,1 * * *'
    # cron表达式，时区是UTC时间，比我们早8小时，如上所表示的是每天0点0分（24点整）和早上9点
    # 建议每个人通过设置 GitHub Environments 的方式来设定为自己的目标运行时间（详细设置方法见文档说明）
  watch:
    types: [started]

jobs:
  build:

    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Run
      uses: GabrielBB/xvfb-action@v1
      with:
        run: dotnet run
      env: 
        CONF: ${{ secrets.CONF }}
