name: Run

on:
    schedule:
    - cron: '0 8 * * *'

jobs:
  build:

    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Run
      uses: GabrielBB/xvfb-action@v1
      with:
        run: dotnet run
      env: 
        CONF: ${{ secrets.CONF }}
